### ISSUE TITLE
UWO Certification fork

### ISSUE THREAD

**Issue by ottenhoff** [sakaicontrib/certification#7]
I propose that we replace master with UWO's fork of certification. AFAICT, they have completely different commit histories.... does anyone know if there is a common ancestor we can use to merge the commit histories?

Anyone have thoughts here?

**Comment by bjones86** [comment]
I contributed all of Western's customizations to the master branch of sakaicontrib/certification under SAK-32126. After that was all merged I got rid of the uwo-svn branch.

**Comment by ottenhoff** [comment]
Wow, totally missed that PR and commit .... OK, closing this issue.

**Comment by bjones86** [comment]
No worries!
